server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, immutable";
  }

  location = /admin {
    try_files /admin.html =404;
  }

  location ^~ /admin/ {
    try_files $uri $uri/ /admin.html;
  }

  location = /h5 {
    try_files /h5.html =404;
  }

  location ^~ /h5/ {
    try_files $uri $uri/ /h5.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
